### ISSUE TITLE
[FEATURE REQUEST] Non-Mutation of Database While Running Package

### ISSUE THREAD

**Issue by TheCedarPrince** [MechanicalRabbit/OHDSICohortExpressions.jl#4]
Hi @xitology and @clarkevans,

Hope you all are doing great!

I have no idea how possible this is, but would it be feasible to make it such that when I run OHDSICohortExpressions, that the original database the package runs on does not create cohort tables or empty tables for cohort statistics? I would much prefer those tables to be created outside the database as some databases I work on are either read only or lack back-ups do to storage constraints. Is this something possible to do?

Thanks! 

~ tcp :deciduous_tree:

**Comment by clarkevans** [comment]
@TheCedarPrince In [v0.2.0](https://github.com/MechanicalRabbit/OHDSICohortExpressions.jl/releases/tag/v0.2.0), the API for this library is changed to support this request. We are no longer writing to the table. You could directly query the data, or use an ```"INSERT INTO .. SELECT FROM ($query)"``` where `$query` is the rendered SQL. If this meets your needs, we could mark this as complete.

See also  #2

**Comment by TheCedarPrince** [comment]
Oh ok -- thanks @clarkevans !
